const indiaLocations = [
{ city: "Adilabad", pin: "504001", district: "Adilabad" },
{ city: "Adoni", pin: "518301", district: "Kurnool" },
{ city: "Akiveedu", pin: "534235", district: "West Godavari" },
{ city: "Akkayapalle", pin: "518003", district: "Kurnool" },
{ city: "Alamanda", pin: "535145", district: "Vizianagaram" },
{ city: "Alampur", pin: "509152", district: "Mahbubnagar" },
{ city: "Alur", pin: "518395", district: "Kurnool" },
{ city: "Amalapuram", pin: "533201", district: "East Godavari" },
{ city: "Amudalapalle", pin: "517213", district: "Chittoor" },
{ city: "Anakapalle", pin: "531001", district: "Visakhapatnam" },
{ city: "Anantapur", pin: "515001", district: "Anantapur" },
{ city: "Araku Valley", pin: "531151", district: "Visakhapatnam" },
{ city: "Atmakur", pin: "518422", district: "Kurnool" },
{ city: "Attili", pin: "534134", district: "West Godavari" },
{ city: "Avanigadda", pin: "521121", district: "Krishna" },
{ city: "Bapatla", pin: "522101", district: "Guntur" },
{ city: "Badvel", pin: "516227", district: "Kadapa" },
{ city: "Banganapalle", pin: "518124", district: "Kurnool" },
{ city: "Bandarulanka", pin: "533221", district: "East Godavari" },
{ city: "Bapatla Bazar", pin: "522102", district: "Guntur" },
{ city: "Bethamcherla", pin: "518599", district: "Kurnool" },
{ city: "Bhimadol", pin: "534425", district: "West Godavari" },
{ city: "Bhimavaram", pin: "534201", district: "West Godavari" },
{ city: "Bobbili", pin: "535558", district: "Vizianagaram" },
{ city: "Buchireddipalem", pin: "524305", district: "Nellore" },
{ city: "Chandragiri", pin: "517101", district: "Chittoor" },
{ city: "Cheepurupalli", pin: "535128", district: "Vizianagaram" },
{ city: "Chintalapudi", pin: "534460", district: "West Godavari" },
{ city: "Chilakaluripet", pin: "522616", district: "Guntur" },
{ city: "Chirala", pin: "523155", district: "Prakasam" },
{ city: "Chittoor", pin: "517001", district: "Chittoor" },
{ city: "Darsi", pin: "523247", district: "Prakasam" },
{ city: "Devarapalle", pin: "534313", district: "West Godavari" },
{ city: "Dhone", pin: "518222", district: "Kurnool" },
{ city: "Dondapudi", pin: "534318", district: "West Godavari" },
{ city: "Doleswram", pin: "533125", district: "East Godavari" },
{ city: "Draksharamam", pin: "533262", district: "East Godavari" },
{ city: "Eluru", pin: "534001", district: "West Godavari" },
{ city: "Etikoppaka", pin: "531082", district: "Visakhapatnam" },
{ city: "Gajuwaka", pin: "530026", district: "Visakhapatnam" },
{ city: "Gannavaram", pin: "521101", district: "Krishna" },
{ city: "Giddalur", pin: "523357", district: "Prakasam" },
{ city: "Gudivada", pin: "521301", district: "Krishna" },
{ city: "Gooty", pin: "515401", district: "Anantapur" },
{ city: "Gudur", pin: "524101", district: "Nellore" },
{ city: "Gajapatinagaram", pin: "535270", district: "Vizianagaram" },
{ city: "Gollaprolu", pin: "533449", district: "East Godavari" },
{ city: "Gopalapuram", pin: "534312", district: "West Godavari" },
{ city: "Guntakal", pin: "515801", district: "Anantapur" },
{ city: "Guntur", pin: "522002", district: "Guntur" },
{ city: "Hindupur", pin: "515201", district: "Anantapur" },
{ city: "Ichchapuram", pin: "532312", district: "Srikakulam" },
{ city: "Jaggampet", pin: "533435", district: "East Godavari" },
{ city: "Jammalamadugu", pin: "516434", district: "Kadapa" },
{ city: "Jangareddigudem", pin: "534447", district: "West Godavari" },
{ city: "Kadiri", pin: "515591", district: "Anantapur" },
{ city: "Kadapa", pin: "516001", district: "Kadapa" },
{ city: "Kakinada", pin: "533001", district: "East Godavari" },
{ city: "Kallur", pin: "518003", district: "Kurnool" },
{ city: "Kanigiri", pin: "523230", district: "Prakasam" },
{ city: "Kavali", pin: "524201", district: "Nellore" },
{ city: "Kalyandurg", pin: "515761", district: "Anantapur" },
{ city: "Kanchikacherla", pin: "521180", district: "Krishna" },
{ city: "Koduru", pin: "524366", district: "Nellore" },
{ city: "Kondapalli", pin: "521228", district: "Krishna" },
{ city: "Kovvur", pin: "534350", district: "West Godavari" },
{ city: "Kothapet", pin: "533223", district: "East Godavari" },
{ city: "Kottapalli", pin: "515701", district: "Anantapur" },
{ city: "Krosuru", pin: "522410", district: "Guntur" },
{ city: "Kudappam", pin: "517425", district: "Chittoor" },
{ city: "Machilipatnam", pin: "521001", district: "Krishna" },
{ city: "Madanpalle", pin: "517325", district: "Chittoor" },
{ city: "Madugula", pin: "531027", district: "Visakhapatnam" },
{ city: "Mandapeta", pin: "533308", district: "East Godavari" },
{ city: "Markapur", pin: "523316", district: "Prakasam" },
{ city: "Macharla", pin: "522426", district: "Guntur" },
{ city: "Mangalagiri", pin: "522503", district: "Guntur" },
{ city: "Medarametta", pin: "523211", district: "Prakasam" },
{ city: "Midthur", pin: "518405", district: "Kurnool" },
{ city: "Mummidivaram", pin: "533216", district: "East Godavari" },
{ city: "Mayadukur", pin: "516172", district: "Kadapa" },
{ city: "Narsaraopet", pin: "522601", district: "Guntur" },
{ city: "Narsannapeta", pin: "532421", district: "Srikakulam" },
{ city: "Nandyal", pin: "518501", district: "Kurnool" },
{ city: "Narsapur", pin: "534275", district: "West Godavari" },
{ city: "Narsipatnam", pin: "531116", district: "Visakhapatnam" },
{ city: "Nellore", pin: "524001", district: "Nellore" },
{ city: "Nuzvid", pin: "521201", district: "Krishna" },
{ city: "Ongole", pin: "523001", district: "Prakasam" },
{ city: "Palasa", pin: "532221", district: "Srikakulam" },
{ city: "Peddapuram", pin: "533437", district: "East Godavari" },
{ city: "Piduguralla", pin: "522413", district: "Guntur" },
{ city: "Pithapuram", pin: "533450", district: "East Godavari" },
{ city: "Proddatur", pin: "516360", district: "Kadapa" },
{ city: "Pulivendula", pin: "516390", district: "Kadapa" },
{ city: "Punganur", pin: "517247", district: "Chittoor" },
{ city: "Puttaparthi", pin: "515134", district: "Anantapur" },
{ city: "Rajahmundry", pin: "533101", district: "East Godavari" },
{ city: "Rajampet", pin: "516115", district: "Kadapa" },
{ city: "Ramachandrapuram", pin: "533255", district: "East Godavari" },
{ city: "Razole", pin: "533248", district: "East Godavari" },
{ city: "Rayakollu", pin: "518583", district: "Kurnool" },
{ city: "Renigunta", pin: "517520", district: "Chittoor" },
{ city: "Ripalle", pin: "534307", district: "West Godavari" },
{ city: "Rippatla", pin: "531034", district: "Visakhapatnam" },
{ city: "Saluru", pin: "535591", district: "Vijayanagaram" },
{ city: "Satyanarayanapuram", pin: "520011", district: "Krishna" },
{ city: "Sajjapuram", pin: "534440", district: "West Godavari" },
{ city: "Sangam", pin: "524306", district: "Nellore" },
{ city: "Sanjeevaraipet", pin: "522002", district: "Guntur" },
{ city: "Satyamangalam", pin: "515731", district: "Anantapur" },
{ city: "Serampalem", pin: "534327", district: "West Godavari" },
{ city: "Shankarampet", pin: "531087", district: "Visakhapatnam" },
{ city: "Srikakulam", pin: "532001", district: "Srikakulam" },
{ city: "Srikalehasti", pin: "517644", district: "Chittoor" },
{ city: "Srirampuram", pin: "533449", district: "East Godavari" },
{ city: "Sompalli", pin: "517257", district: "Chittoor" },
{ city: "Tadepallegudem", pin: "534101", district: "West Godavari" },
{ city: "Tadepalli", pin: "522501", district: "Guntur" },
{ city: "Tadepudi", pin: "531116", district: "Visakhapatnam" },
{ city: "Tallapudi", pin: "534341", district: "West Godavari" },
{ city: "Tadipatri", pin: "515411", district: "Anantapur" },
{ city: "Tanuku", pin: "534211", district: "West Godavari" },
{ city: "Tirupati", pin: "517501", district: "Chittoor" },
{ city: "Tiruvarur", pin: "521235", district: "Krishna" },
{ city: "Tiruvottiyur", pin: "531055", district: "Visakhapatnam" },
{ city: "Telikicherla", pin: "518281", district: "Kurnool" },
{ city: "Thottam", pin: "531033", district: "Visakhapatnam" },
{ city: "Tripurantaka", pin: "523334", district: "Prakasam" },
{ city: "Vinukonda", pin: "522647", district: "Guntur" },
{ city: "Vadlamudi", pin: "522213", district: "Guntur" },
{ city: "Vadlamuru", pin: "534427", district: "West Godavari" },
{ city: "Velagapuram", pin: "515822", district: "Anantapur" },
{ city: "Vellore", pin: "524228", district: "Nellore" },
{ city: "Venkatagiri", pin: "524132", district: "Nellore" },
{ city: "Venkatagiri Kota", pin: "517424", district: "Chittoor" },
{ city: "Venkatapuram", pin: "532195", district: "Srikakulam" },
{ city: "Vijayawada", pin: "520001", district: "Krishna" },
{ city: "Vizianagaram", pin: "535001", district: "Vizianagaram" },
{ city: "Vijayapuram", pin: "524305", district: "Nellore" },
{ city: "Visakhapatnam", pin: "530001", district: "Visakhapatnam" },
{ city: "Visakha Airport", pin: "531040", district: "Visakhapatnam" },
{ city: "Vadirai", pin: "534447", district: "West Godavari" },
{ city: "Yanam", pin: "533464", district: "East Godavari" },
{ city: "Yadavapalem", pin: "524410", district: "Nellore" },
{ city: "Yerragudipadu", pin: "516360", district: "Cuddapah" },
{ city: "Yerraguntla", pin: "516312", district: "Cuddapah" },
{ city: "Yerrapahad", pin: "518395", district: "Kurnool" },
{ city: "Yerravaram", pin: "533233", district: "East Godavari" },
{ city: "Jiyanagar", pin: "530031", district: "Visakhapatnam" },
{ city: "Kotha Kota", pin: "509625", district: "Mahbubnagar" },
{ city: "Kothapalli", pin: "515774", district: "Anantapur" },
{ city: "Kothage", pin: "518466", district: "Kurnool" },
{ city: "Kondur", pin: "522212", district: "Guntur" },
{ city: "Konaseema", pin: "533001", district: "East Godavari" },
{ city: "Kantar", pin: "518004", district: "Kurnool" },
{ city: "Kanthal", pin: "515561", district: "Anantapur" },
{ city: "Kurnool Camp", pin: "518002", district: "Kurnool" },
{ city: "Krishna Lanka", pin: "520013", district: "Krishna" },
{ city: "Krishna Nagar", pin: "534202", district: "West Godavari" },
{ city: "Kutubullapuram", pin: "517234", district: "Chittoor" },
{ city: "Mandavali", pin: "533436", district: "East Godavari" },
{ city: "Mylavaram", pin: "521230", district: "Krishna" },
{ city: "Mandapeta", pin: "533308", district: "East Godavari" },
{ city: "Mulug", pin: "534182", district: "West Godavari" },
{ city: "Musipalli", pin: "522329", district: "Guntur" },
{ city: "Mutyalreddypalem", pin: "524004", district: "Nellore" },
{ city: "Nandaval", pin: "524405", district: "Nellore" },
{ city: "Nagayalanka", pin: "521120", district: "Krishna" },
{ city: "Naugulapalem", pin: "533297", district: "East Godavari" },
{ city: "Nandipalem", pin: "522017", district: "Guntur" },
{ city: "Narayanpur", pin: "516003", district: "Cuddapah" },
{ city: "Narayanam", pin: "523286", district: "Prakasam" },
{ city: "Navalpally", pin: "517130", district: "Chittoor" },
{ city: "Nakkala", pin: "521256", district: "Krishna" },
{ city: "Nellore Bazaar", pin: "524003", district: "Nellore" },
{ city: "Nilapattu", pin: "517581", district: "Chittoor" },
{ city: "Nuzvur", pin: "534156", district: "West Godavari" },
{ city: "Odalareddy", pin: "518001", district: "Kurnool" },
{ city: "Odalaru", pin: "533242", district: "East Godavari" },
{ city: "Odhara", pin: "532222", district: "Srikakulam" },
{ city: "Omnagar", pin: "524308", district: "Nellore" },
{ city: "Omkarpalem", pin: "524002", district: "Nellore" },
{ city: "Ottapalem", pin: "533237", district: "East Godavari" },
{ city: "Pagaldu", pin: "533343", district: "East Godavari" },
{ city: "Padur", pin: "515432", district: "Anantapur" },
{ city: "Payyanpalem", pin: "534235", district: "West Godavari" },
{ city: "Pallam", pin: "524215", district: "Nellore" },
{ city: "Pallampet", pin: "517127", district: "Chittoor" },
{ city: "Pallepalem", pin: "522265", district: "Guntur" },
{ city: "Panchalkodur", pin: "522409", district: "Guntur" },
{ city: "Patsur", pin: "522437", district: "Guntur" },
{ city: "Paral", pin: "532408", district: "Srikakulam" },
{ city: "Perur", pin: "533285", district: "East Godavari" },
{ city: "Peruru", pin: "517586", district: "Chittoor" },
{ city: "Pinnellala", pin: "523247", district: "Prakasam" },
{ city: "Pinvaprol", pin: "534313", district: "West Godavari" },
{ city: "Piralam", pin: "523001", district: "Prakasam" },
{ city: "Pippalli", pin: "532263", district: "Srikakulam" },
{ city: "Pisap", pin: "533103", district: "East Godavari" },
{ city: "Pullaram", pin: "522423", district: "Guntur" },
{ city: "Kochi", pin: "682007", district: "Ernakulam" },
{ city: "Ramanagara", pin: "534351", district: "West Godavari" },
{ city: "Ramapuram", pin: "534457", district: "West Godavari" },
{ city: "Ramtek", pin: "534305", district: "West Godavari" },
{ city: "Rampuram", pin: "524305", district: "Nellore" },
{ city: "Rama", pin: "533242", district: "East Godavari" },
{ city: "Ratnam", pin: "533245", district: "East Godavari" },
{ city: "Reddipalem", pin: "533291", district: "East Godavari" },
{ city: "Revur", pin: "534301", district: "West Godavari" },
{ city: "Sattenapalli", pin: "522403", district: "Guntur" },
{ city: "Satyanagar", pin: "532221", district: "Srikakulam" },
{ city: "Sivapuram", pin: "534305", district: "West Godavari" },
{ city: "Sikanderpuram", pin: "516231", district: "Cuddapah" },
{ city: "Siddhapuram", pin: "533346", district: "East Godavari" },
{ city: "Suratpur", pin: "517231", district: "Chittoor" },
{ city: "Surpur", pin: "518401", district: "Kurnool" },
{ city: "Tadupulem", pin: "533437", district: "East Godavari" },
{ city: "Tiruputhur", pin: "515185", district: "Anantapur" },
{ city: "Tirupul", pin: "522408", district: "Guntur" },
{ city: "Tiruprakash", pin: "523247", district: "Prakasam" },
{ city: "Tiruppur", pin: "532195", district: "Srikakulam" },
{ city: "Tirupati", pin: "517501", district: "Chittoor" },
{ city: "Tiruppur", pin: "524307", district: "Nellore" },
{ city: "Tiruvarur", pin: "521235", district: "Krishna" },
{ city: "Tiruvotti", pin: "531055", district: "Visakhapatnam" },
{ city: "Telikicherla", pin: "518281", district: "Kurnool" },
{ city: "Thottam", pin: "531033", district: "Visakhapatnam" },
{ city: "Tripurantaka", pin: "523334", district: "Prakasam" },
{ city: "Vinukonda", pin: "522647", district: "Guntur" },
{ city: "Vadlamudi", pin: "522213", district: "Guntur" },
{ city: "Vadlamuru", pin: "534427", district: "West Godavari" },
{ city: "Velagapuram", pin: "515822", district: "Anantapur" },
{ city: "Vellore", pin: "524228", district: "Nellore" },
{ city: "Venkatagiri", pin: "524132", district: "Nellore" },
{ city: "Venkatagiri Kota", pin: "517424", district: "Chittoor" },
{ city: "Venkatapuram", pin: "532195", district: "Srikakulam" },
{ city: "Vijayawada", pin: "520001", district: "Krishna" },
{ city: "Vizianagaram", pin: "535001", district: "Vizianagaram" },
{ city: "Vijayapuram", pin: "524305", district: "Nellore" },
{ city: "Visakhapatnam", pin: "530001", district: "Visakhapatnam" },
{ city: "Visakha Airport", pin: "531040", district: "Visakhapatnam" },
{ city: "Vadirai", pin: "534447", district: "West Godavari" },
{ city: "Yanam", pin: "533464", district: "East Godavari" },
{ city: "Yadavapalem", pin: "524410", district: "Nellore" },
{ city: "Yerragudipadu", pin: "516360", district: "Cuddapah" },
{ city: "Yerraguntla", pin: "516312", district: "Cuddapah" },
{ city: "Yerrapahad", pin: "518395", district: "Kurnool" },
{ city: "Yerravaram", pin: "533233", district: "East Godavari" },
{ city: "Jiyanagar", pin: "530031", district: "Visakhapatnam" },
{ city: "Kotha Kota", pin: "509625", district: "Mahbubnagar" },
{ city: "Kothapalli", pin: "515774", district: "Anantapur" },
{ city: "Kothage", pin: "518466", district: "Kurnool" },
{ city: "Kondur", pin: "522212", district: "Guntur" },
{ city: "Konaseema", pin: "533001", district: "East Godavari" },
{ city: "Kantar", pin: "518004", district: "Kurnool" },
{ city: "Kanthal", pin: "515561", district: "Anantapur" },
{ city: "Kurnool Camp", pin: "518002", district: "Kurnool" },
{ city: "Krishna Lanka", pin: "520013", district: "Krishna" },
{ city: "Krishna Nagar", pin: "534202", district: "West Godavari" },
{ city: "Kutubullapuram", pin: "517234", district: "Chittoor" },
{ city: "Mandavali", pin: "533436", district: "East Godavari" },
{ city: "Mylavaram", pin: "521230", district: "Krishna" },
{ city: "Mandapeta", pin: "533308", district: "East Godavari" },
{ city: "Mulug", pin: "534182", district: "West Godavari" },
{ city: "Musipalli", pin: "522329", district: "Guntur" },
{ city: "Mutyalreddypalem", pin: "524004", district: "Nellore" },
{ city: "Nandaval", pin: "524405", district: "Nellore" },
{ city: "Nagayalanka", pin: "521120", district: "Krishna" },
{ city: "Nagulapalem", pin: "533297", district: "East Godavari" },
{ city: "Nandipalem", pin: "522017", district: "Guntur" },
{ city: "Narayanpur", pin: "516003", district: "Kadapa" },
{ city: "Narayanam", pin: "523286", district: "Prakasam" },
{ city: "Navalpally", pin: "517130", district: "Chittoor" },
{ city: "Nakkala", pin: "521256", district: "Krishna" },
{ city: "Nellore Bazaar", pin: "524003", district: "Nellore" },
{ city: "Nilapattu", pin: "517581", district: "Chittoor" },
{ city: "Nuzvur", pin: "534156", district: "West Godavari" },
{ city: "Odalareddy", pin: "518001", district: "Kurnool" },
{ city: "Odalaru", pin: "533242", district: "East Godavari" },
{ city: "Odhara", pin: "532222", district: "Srikakulam" },
{ city: "Omnagar", pin: "524308", district: "Nellore" },
{ city: "Omkarpalem", pin: "524002", district: "Nellore" },
{ city: "Ottapalem", pin: "533237", district: "East Godavari" },
{ city: "Pagaldu", pin: "533343", district: "East Godavari" },
{ city: "Padur", pin: "515432", district: "Anantapur" },
{ city: "Payyanpalem", pin: "534235", district: "West Godavari" },
{ city: "Pallam", pin: "524215", district: "Nellore" },
{ city: "Pallampet", pin: "517127", district: "Chittoor" },
{ city: "Pallepalem", pin: "522265", district: "Guntur" },
{ city: "Panchalkodur", pin: "522409", district: "Guntur" },
{ city: "Patsur", pin: "522437", district: "Guntur" },
{ city: "Paral", pin: "532408", district: "Srikakulam" },
{ city: "Perur", pin: "533285", district: "East Godavari" },
{ city: "Peruru", pin: "517586", district: "Chittoor" },
{ city: "Pinnela", pin: "523247", district: "Prakasam" },
{ city: "Pinvaprol", pin: "534313", district: "West Godavari" },
{ city: "Piralam", pin: "523001", district: "Prakasam" },
{ city: "Pippalli", pin: "532263", district: "Srikakulam" },
{ city: "Pisap", pin: "533103", district: "East Godavari" },
{ city: "Kodur", pin: "516101", district: "Cuddapah" },
{ city: "Kotapalle", pin: "534325", district: "West Godavari" },
{ city: "Kothavalli", pin: "534310", district: "West Godavari" },
{ city: "Kreetipalem", pin: "534301", district: "West Godavari" },
{ city: "Kudulla", pin: "518433", district: "Kurnool" },
{ city: "Kundur", pin: "533297", district: "East Godavari" },
{ city: "Kuppam", pin: "517425", district: "Chittoor" },
{ city: "Kuppam", pin: "517425", district: "Chittoor" },
{ city: "Kurumula", pin: "534101", district: "West Godavari" },
{ city: "Kuruppa", pin: "534302", district: "West Godavari" },
{ city: "Kudumpally", pin: "518221", district: "Kurnool" },
{ city: "Lalpuram", pin: "533217", district: "East Godavari" },
{ city: "Laddupuram", pin: "533234", district: "East Godavari" },
{ city: "Madapuram", pin: "534301", district: "West Godavari" },
{ city: "Madanapalem", pin: "533201", district: "East Godavari" },
{ city: "Madugula", pin: "531027", district: "Visakhapatnam" },
{ city: "Manchipuram", pin: "534340", district: "West Godavari" },
{ city: "Mansiguda", pin: "534312", district: "West Godavari" },
{ city: "Mayurapuri", pin: "521230", district: "Krishna" },
{ city: "Medikonda", pin: "534305", district: "West Godavari" },
{ city: "Machilipatnam", pin: "521001", district: "Krishna" },
{ city: "Macherla", pin: "522426", district: "Guntur" },
{ city: "Mangalagiri", pin: "522503", district: "Guntur" },
{ city: "Mandavali", pin: "533436", district: "East Godavari" },
{ city: "Mandapeta", pin: "533308", district: "East Godavari" },
{ city: "Mandalapalem", pin: "534332", district: "West Godavari" },
{ city: "Mandalpuri", pin: "534335", district: "West Godavari" },
{ city: "Mardevra", pin: "534338", district: "West Godavari" },
{ city: "Madurapuri", pin: "515001", district: "Anantapur" },
{ city: "Medak", pin: "518346", district: "Kurnool" },
{ city: "Medpuram", pin: "533218", district: "East Godavari" },
{ city: "Medikonda", pin: "534305", district: "West Godavari" },
{ city: "Mihir", pin: "532221", district: "Srikakulam" },
{ city: "Motipuram", pin: "534310", district: "West Godavari" },
{ city: "Mummidivaram", pin: "533216", district: "East Godavari" },
{ city: "Muralipuram", pin: "533433", district: "East Godavari" },
{ city: "Murugapuram", pin: "534326", district: "West Godavari" },
{ city: "Mydukur", pin: "516172", district: "Cuddapah" },
{ city: "Nandigama", pin: "521214", district: "Krishna" },
{ city: "Narasaropet", pin: "522601", district: "Guntur" },
{ city: "Narasimhagudem", pin: "534313", district: "West Godavari" },
{ city: "Narsipet", pin: "533234", district: "East Godavari" },
{ city: "Narsipuram", pin: "533221", district: "East Godavari" },
{ city: "Nandyal", pin: "518501", district: "Kurnool" },
{ city: "Narasimhapuram", pin: "533237", district: "East Godavari" },
{ city: "Nellore", pin: "524001", district: "Nellore" },
{ city: "Nellore Bazaar", pin: "524003", district: "Nellore" },
{ city: "Nuzvid", pin: "521201", district: "Krishna" },
{ city: "Ongole", pin: "523001", district: "Prakasam" },
{ city: "Palasa", pin: "532221", district: "Srikakulam" },
{ city: "Peddapuram", pin: "533437", district: "East Godavari" },
{ city: "Piduguralla", pin: "522413", district: "Guntur" },
{ city: "Pithapuram", pin: "533450", district: "East Godavari" },
{ city: "Proddatur", pin: "516360", district: "Cuddapah" },
{ city: "Pulivendul", pin: "516390", district: "Cuddapah" },
{ city: "Panganur", pin: "517247", district: "Chittoor" },
{ city: "Puttaparthi", pin: "515134", district: "Anantapur" },
{ city: "Rajamahendravaram", pin: "533101", district: "East Godavari" },
{ city: "Rajampet", pin: "516115", district: "Cuddapah" },
{ city: "Ramachandrapuram", pin: "533255", district: "East Godavari" },
{ city: "Ramanagareddy", pin: "518345", district: "Kurnool" },
{ city: "Rampuram", pin: "524305", district: "Nellore" },
{ city: "Ramarajapuram", pin: "534332", district: "West Godavari" },
{ city: "Ratnam", pin: "533245", district: "East Godavari" },
{ city: "Renigunta", pin: "517520", district: "Chittoor" },
{ city: "Revur", pin: "534301", district: "West Godavari" },
{ city: "Sattenapalli", pin: "522403", district: "Guntur" },
{ city: "Satyanagar", pin: "532221", district: "Srikakulam" },
{ city: "Sivapuram", pin: "534305", district: "West Godavari" },
{ city: "Sikanderpuram", pin: "516231", district: "Cuddapah" },
{ city: "Siddhapuram", pin: "533346", district: "East Godavari" },
{ city: "Suratpur", pin: "517231", district: "Chittoor" },
{ city: "Surpur", pin: "518401", district: "Kurnool" },
{ city: "Tadupulem", pin: "533437", district: "East Godavari" },
{ city: "Tiruputhur", pin: "515185", district: "Anantapur" },
{ city: "Tirupul", pin: "522408", district: "Guntur" },
{ city: "Tiruprakash", pin: "523247", district: "Prakasam" },
{ city: "Tirupur", pin: "532195", district: "Srikakulam" },
{ city: "Tirupati", pin: "517501", district: "Chittoor" },
{ city: "Tirupur", pin: "524307", district: "Nellore" },
{ city: "Tiruvarur", pin: "521235", district: "Krishna" },
{ city: "Tiruvotty", pin: "531055", district: "Visakhapatnam" },
{ city: "Telikicherla", pin: "518281", district: "Kurnool" },
{ city: "Thottam", pin: "531033", district: "Visakhapatnam" },
{ city: "Tripurantaka", pin: "523334", district: "Prakasam" },
{ city: "Vinukonda", pin: "522647", district: "Guntur" },
{ city: "Vadlamudi", pin: "522213", district: "Guntur" },
{ city: "Vadlamuru", pin: "534427", district: "West Godavari" },
{ city: "Velagapuram", pin: "515822", district: "Anantapur" },
{ city: "Vellore", pin: "524228", district: "Nellore" },
{ city: "Venkatagiri", pin: "524132", district: "Nellore" },
{ city: "Venkatagiri Kota", pin: "517424", district: "Chittoor" },
{ city: "Venkatapuram", pin: "532195", district: "Srikakulam" },
{ city: "Vijayawada", pin: "520001", district: "Krishna" },
{ city: "Vizianagaram", pin: "535001", district: "Vizianagaram" },
{ city: "Vijayapuram", pin: "524305", district: "Nellore" },
{ city: "Visakhapatnam", pin: "530001", district: "Visakhapatnam" },
{ city: "Visakha Airport", pin: "531040", district: "Visakhapatnam" },
{ city: "Vadirai", pin: "534447", district: "West Godavari" },
{ city: "Yanam", pin: "533464", district: "East Godavari" },
{ city: "Yadavapalem", pin: "524410", district: "Nellore" },
{ city: "Yerragudipadu", pin: "516360", district: "Cuddapah" },
{ city: "Yerraguntla", pin: "516312", district: "Cuddapah" },
{ city: "Yerrapahad", pin: "518395", district: "Kurnool" },
{ city: "Yerravaram", pin: "533233", district: "East Godavari" },
{ city: "Jiyanagar", pin: "530031", district: "Visakhapatnam" },
{ city: "Kotha Kota", pin: "509625", district: "Mahbubnagar" },
{ city: "Kothapalli", pin: "515774", district: "Anantapur" },
{ city: "Kothage", pin: "518466", district: "Kurnool" },
{ city: "Kondur", pin: "522212", district: "Guntur" },
{ city: "Konaseema", pin: "533001", district: "East Godavari" },
{ city: "Kantar", pin: "518004", district: "Kurnool" },
{ city: "Kanthal", pin: "515561", district: "Anantapur" },
{ city: "Kurnool Camp", pin: "518002", district: "Kurnool" },
{ city: "Krishna Lanka", pin: "520013", district: "Krishna" },
{ city: "Krishna Nagar", pin: "534202", district: "West Godavari" },
{ city: "Kutubullapuram", pin: "517234", district: "Chittoor" },
{ city: "Mandavali", pin: "533436", district: "East Godavari" },
{ city: "Mylavaram", pin: "521230", district: "Krishna" },
{ city: "Mandapet", pin: "533308", district: "East Godavari" },
{ city: "Mulug", pin: "534182", district: "West Godavari" },
{ city: "Musipalli", pin: "522329", district: "Guntur" },
{ city: "Mutyalreddypalem", pin: "524004", district: "Nellore" },
{ city: "Nandaval", pin: "524405", district: "Nellore" },
{ city: "Nagayalanka", pin: "521120", district: "Krishna" },
{ city: "Nagulapalem", pin: "533297", district: "East Godavari" },
{ city: "Nandipalem", pin: "522017", district: "Guntur" },
{ city: "Narayanpur", pin: "516003", district: "Cuddapah" },
{ city: "Narayanam", pin: "523286", district: "Prakasam" },
{ city: "Navalpalli", pin: "517130", district: "Chittoor" },
{ city: "Nakkala", pin: "521256", district: "Krishna" },
{ city: "Nellore Bazaar", pin: "524003", district: "Nellore" },
{ city: "Nilapattu", pin: "517581", district: "Chittoor" },
{ city: "Nuzvur", pin: "534156", district: "West Godavari" },
{ city: "Odalareddy", pin: "518001", district: "Kurnool" },
{ city: "Odalaru", pin: "533242", district: "East Godavari" },
{ city: "Odhara", pin: "532222", district: "Srikakulam" },
{ city: "Omnagar", pin: "524308", district: "Nellore" },
{ city: "Omkarpalem", pin: "524002", district: "Nellore" },
{ city: "Ottapalem", pin: "533237", district: "East Godavari" },
{ city: "Pagaldu", pin: "533343", district: "East Godavari" },
{ city: "Padur", pin: "515432", district: "Anantapur" },
{ city: "Payyanpalem", pin: "534235", district: "West Godavari" },
{ city: "Pallam", pin: "524215", district: "Nellore" },
{ city: "Pallampet", pin: "517127", district: "Chittoor" },
{ city: "Pallepalem", pin: "522265", district: "Guntur" },
{ city: "Panchalkodur", pin: "522409", district: "Guntur" },
{ city: "Patsur", pin: "522437", district: "Guntur" },
{ city: "Paral", pin: "532408", district: "Srikakulam" },
{ city: "Perur", pin: "533285", district: "East Godavari" },
{ city: "Peruru", pin: "517586", district: "Chittoor" },
{ city: "Pinnella", pin: "523247", district: "Prakasam" },
{ city: "Pinvaprol", pin: "534313", district: "West Godavari" },
{ city: "Piralam", pin: "523001", district: "Prakasam" },
{ city: "Pippalli", pin: "532263", district: "Srikakulam" },
{ city: "Pisap", pin: "533103", district: "East Godavari" },
{ city: "Pullaram", pin: "522423", district: "Guntur" },
{ city: "Rajamahendravaram", pin: "533101", district: "East Godavari" },
{ city: "Rajampet", pin: "516115", district: "Cuddapah" },
{ city: "Ramachandrapuram", pin: "533255", district: "East Godavari" },
{ city: "Ramnagar", pin: "534351", district: "West Godavari" },
{ city: "Ramapuram", pin: "534457", district: "West Godavari" },
{ city: "Ramtek", pin: "534305", district: "West Godavari" },
{ city: "Rampuram", pin: "524305", district: "Nellore" },
{ city: "Rama", pin: "533242", district: "East Godavari" },
{ city: "Ratnam", pin: "533245", district: "East Godavari" },
{ city: "Reddipalem", pin: "533291", district: "East Godavari" },
{ city: "Revur", pin: "534301", district: "West Godavari" },
{ city: "Sattenapalli", pin: "522403", district: "Guntur" },
{ city: "Satyanagar", pin: "532221", district: "Srikakulam" },
{ city: "Sivapuram", pin: "534305", district: "West Godavari" },
{ city: "Sikanderpuram", pin: "516231", district: "Kadapa" },
{ city: "Siddhapuram", pin: "533346", district: "East Godavari" },
{ city: "Suratpur", pin: "517231", district: "Chittoor" },
{ city: "Surpur", pin: "518401", district: "Kurnool" },
{ city: "Tadupulem", pin: "533437", district: "East Godavari" },
{ city: "Tiruputhur", pin: "515185", district: "Anantapur" },
{ city: "Tirupul", pin: "522408", district: "Guntur" },
{ city: "Tiruprakash", pin: "523247", district: "Prakasam" },
{ city: "Tirupur", pin: "532195", district: "Srikakulam" },
{ city: "Tirupati", pin: "517501", district: "Chittoor" },
{ city: "Tirupur", pin: "524307", district: "Nellore" },
{ city: "Tiruvarur", pin: "521235", district: "Krishna" },
{ city: "Tiruvotti", pin: "531055", district: "Visakhapatnam" },
{ city: "Telikicherla", pin: "518281", district: "Kurnool" },
{ city: "Thottam", pin: "531033", district: "Visakhapatnam" },
{ city: "Tripurantaka", pin: "523334", district: "Prakasam" },
{ city: "Vinukonda", pin: "522647", district: "Guntur" },
{ city: "Vadlamudi", pin: "522213", district: "Guntur" },
{ city: "Vadlamuru", pin: "534427", district: "West Godavari" },
{ city: "Velagapuram", pin: "515822", district: "Anantapur" },
{ city: "Vellore", pin: "524228", district: "Nellore" },
{ city: "Venkatagiri", pin: "524132", district: "Nellore" },
{ city: "Venkatagiri Kota", pin: "517424", district: "Chittoor" },
{ city: "Venkatapuram", pin: "532195", district: "Srikakulam" },
{ city: "Vijayawada", pin: "520001", district: "Krishna" },
{ city: "Vizianagaram", pin: "535001", district: "Vizianagaram" },
{ city: "Vijayapuram", pin: "524305", district: "Nellore" },
{ city: "Visakhapatnam", pin: "530001", district: "Visakhapatnam" },
{ city: "Visakha Airport", pin: "531040", district: "Visakhapatnam" },
{ city: "Vadirai", pin: "534447", district: "West Godavari" },
{ city: "Yanam", pin: "533464", district: "East Godavari" },
{ city: "Yadavapalem", pin: "524410", district: "Nellore" },
{ city: "Yerragudipadu", pin: "516360", district: "Cuddapah" },
{ city: "Yerraguntla", pin: "516312", district: "Cuddapah" },
{ city: "Yerrapahad", pin: "518395", district: "Kurnool" },
{ city: "Yerravaram", pin: "533233", district: "East Godavari" },
{ city: "Jiyanagar", pin: "530031", district: "Visakhapatnam" },
{ city: "Kotha Kota", pin: "509625", district: "Mahbubnagar" },
{ city: "Kothapalli", pin: "515774", district: "Anantapur" },
{ city: "Kothage", pin: "518466", district: "Kurnool" },
{ city: "Kondur", pin: "522212", district: "Guntur" },
{ city: "Konaseema", pin: "533001", district: "East Godavari" },
{ city: "Kantar", pin: "518004", district: "Kurnool" },
{ city: "Kanthal", pin: "515561", district: "Anantapur" },
{ city: "Kurnool Camp", pin: "518002", district: "Kurnool" },
{ city: "Krishna Lanka", pin: "520013", district: "Krishna" },
{ city: "Krishna Nagar", pin: "534202", district: "West Godavari" },
{ city: "Kutubullapuram", pin: "517234", district: "Chittoor" },
{ city: "Mandavali", pin: "533436", district: "East Godavari" },
{ city: "Mylavaram", pin: "521230", district: "Krishna" },
{ city: "Mandapet", pin: "533308", district: "East Godavari" },
{ city: "Mulug", pin: "534182", district: "West Godavari" },
{ city: "Musipalli", pin: "522329", district: "Guntur" },
{ city: "Mutyalreddypalem", pin: "524004", district: "Nellore" },
{ city: "Nandaval", pin: "524405", district: "Nellore" },
{ city: "Nagayalanka", pin: "521120", district: "Krishna" },
{ city: "Nagulapalem", pin: "533297", district: "East Godavari" },
{ city: "Nandipalem", pin: "522017", district: "Guntur" },
{ city: "Narayanpur", pin: "516003", district: "Cuddapah" },
{ city: "Narayanam", pin: "523286", district: "Prakasam" },
{ city: "Navalpally", pin: "517130", district: "Chittoor" },
{ city: "Nakkal", pin: "521256", district: "Krishna" },
{ city: "Nellore Bazaar", pin: "524003", district: "Nellore" },
{ city: "Nilapattu", pin: "517581", district: "Chittoor" },
{ city: "Nuzvur", pin: "534156", district: "West Godavari" },
{ city: "Odalareddy", pin: "518001", district: "Kurnool" },
{ city: "Odalaru", pin: "533242", district: "East Godavari" },
{ city: "Odhara", pin: "532222", district: "Srikakulam" },
{ city: "Omnagar", pin: "524308", district: "Nellore" },
{ city: "Omkarpalem", pin: "524002", district: "Nellore" },
{ city: "Ottapalem", pin: "533237", district: "East Godavari" },
{ city: "Pagaldu", pin: "533343", district: "East Godavari" },
{ city: "Padur", pin: "515432", district: "Anantapur" },
{ city: "Payyanpalem", pin: "534235", district: "West Godavari" },
{ city: "Pallam", pin: "524215", district: "Nellore" },
{ city: "Pallampet", pin: "517127", district: "Chittoor" },
{ city: "Pallepalem", pin: "522265", district: "Guntur" },
{ city: "Panchalkodur", pin: "522409", district: "Guntur" },
{ city: "Patsur", pin: "522437", district: "Guntur" },
];

const allCities = indiaLocations.map(item => 
  `${item.city} – ${item.pin} – ${item.district}`
);

function setupAutoSuggest(input) {
  const box = document.createElement("ul");
  box.className = "suggestions";
  input.parentNode.appendChild(box);

  function showSuggestions() {
    const val = input.value.toLowerCase();
    const filtered = val
      ? allCities.filter(item => item.toLowerCase().startsWith(val))
      : allCities;

    box.innerHTML = "";
    filtered.forEach(item => {
      const li = document.createElement("li");
      li.innerHTML = item;
      box.appendChild(li);

      li.addEventListener("click", () => {
        input.value = item;     // पूरा string सेट होगा
        box.style.display = "none";
      });
    });

    box.style.display = filtered.length ? "block" : "none";
  }

  input.addEventListener("focus", showSuggestions);
  input.addEventListener("input", showSuggestions);

  document.addEventListener("click", (e) => {
    if (!e.target.closest(".input-group")) box.style.display = "none";
  });
}

setupAutoSuggest(document.getElementById("pickup"));
setupAutoSuggest(document.getElementById("delivery"));
